exports.queryList={
    USERS_SIGNUP_QUERY : 'INSERT INTO BOOKING.USERS (USER_NAME, USER_EMAIL, USER_PASSWORD, USER_PHONE) VALUES($1,$2,$3,$4)',
    FIND_USERS_ID :'SELECT USER_ID FROM BOOKING.USERS WHERE USER_ID=$1',
    AUTHORIZATION :'SELECT * FROM BOOKING.USERS WHERE USER_EMAIL =$1 AND  USER_PASSWORD =$2',
    USER_CART_ITEMS:'SELECT * FROM BOOKING.BOOKED WHERE USER_ID=$1',
    
    

}